##
# This class is responsible for storing types of each column and 
# generating the final table description that can be used to create
# the table
##
module CsvUtils
  class AutoGeneratedTable

    attr_writer :field_types, :columns
    attr_reader :field_types, :columns
 
    def initialize *args
      options = args.extract_options!
      @columns = options["columns"]
      @file_name = options["table_name"]
      @field_types = Hash.new
    end
   
    ##
    # Gets the column name and the type that it has to set
    # Adds the type to a structure like: {[type => occurences], [type => #_occurances]...}
    # field_types array contains hashes for each column
    # which can have one or more types
    # number of occurances are used to determine the type
    ##
    def set_type(header_name, type)
      if(!@field_types[header_name].nil?)
        found = false
        if(@field_types[header_name].has_key?(type))
          @field_types[header_name][type] += 1
          found = true
        end
        if(!found)
          @field_types[header_name][type] = 1
        end
      else
        typeHash = Hash.new 
        typeHash[type] = 1
        @field_types[header_name] = typeHash
      end
    end

    def get_types_for_display
      typeChecker = TypeChecker.new
      generated_types = Hash.new
      @columns.each do |header|
        generated_types[header] = typeChecker.pick_type_from(@field_types[header])
      end
      return generated_types
    end

    def get_create_table
      typeChecker = TypeChecker.new
      str = "CREATE TABLE `#{@file_name}` ( "
      @columns.each do |header|
        str += "`" + header + "` " + typeChecker.pick_type_from(@field_types[header]) + ", "
      end
      str += "`" + "active_row" + "` " + "VARCHAR(10)" + ", "
      str += "`" + "csv_job_id" + "` " + "INTEGER" + ") "
      puts str
      return str
    end

    def get_all_string_table_schema
      str = "CREATE TABLE `#{@file_name}` ( "
      @columns.each do |header|
        str += "`" + header + "` " + "VARCHAR(256)" + ", "
      end
      str += "`" + "active_row" + "` " + "VARCHAR(10)" + ", "
      str += "`" + "csv_job_id" + "` " + "INTEGER" + ") "
      puts str
      return str      
    end

  end
end
